// src/constans/plans-mock.ts

import { Zap, Gift, Trophy, Star, Crown } from "lucide-react";

export const plans = [
    {
        id: 'standart',
        name: "Standart",
        price: "19,90",
        priceValue: 19.90,
        description: "Gestão básica e acesso ao processo",
        icon: Zap,
        features: [
            "Gestão de comissões",
            "Dashboard básico",
            "Relatórios mensais",
        ],
        available: true,
        popular: true,
        gradient: "from-blue-500 to-cyan-500",
    },
    {
        id: 'growth',
        name: "Growth",
        price: "49,90",
        priceValue: 49.90,
        description: "Sorteios com spread zero",
        icon: Gift,
        features: [
            "Tudo do Standart",
            "Sorteios mensais",
            "Spread zero temporário",
        ],
        available: false,
        popular: false,
        gradient: "from-purple-500 to-pink-500",
    },
    {
        id: 'apoiador',
        name: "Apoiador",
        price: "199,90",
        priceValue: 199.90,
        description: "Benefícios com rentabilidade",
        icon: Trophy,
        features: [
            "Tudo do Growth",
            "Rentabilidade exclusiva",
            "Análises personalizadas",
        ],
        available: false,
        popular: false,
        gradient: "from-orange-500 to-red-500",
    },
    {
        id: 'elite',
        name: "Elite",
        price: "300",
        priceValue: 300.00,
        description: "Spread zero permanente",
        icon: Star,
        features: [
            "Tudo do Apoiador",
            "Spread zero permanente",
            "Relatórios em tempo real",
        ],
        available: false,
        popular: false,
        gradient: "from-emerald-500 to-teal-500",
    },
    {
        id: 'premium',
        name: "Premium",
        price: "500",
        priceValue: 500.00,
        description: "Acesso ao fundo + dividendos",
        icon: Crown,
        features: [
            "Tudo do Elite",
            "Acesso ao fundo exclusivo",
            "Dividendos mensais",
        ],
        available: false,
        popular: false,
        gradient: "from-yellow-500 to-amber-500",
    },
];